### ISSUE TITLE
Release script breaks on npm publish

### ISSUE THREAD

**Issue by rayrutjes** [algolia/chunk-text#1]
The release script does not manage to find credentials from environment.

**Comment by rayrutjes** [comment]
Works fine when running the `bin/release.sh` script directly.
Removed the package.json release script in e534b24.

**Comment by vvo** [comment]
last time I got that it was because yarn release was not working while npm run release was.

**Comment by rayrutjes** [comment]
I think it is unrelated since here I'm using `npm publish`. It's probably that node has no way of accessing the file where credentials live.

**Comment by vvo** [comment]
We faced the exact same issue, using yarn to launch a script that has npm publish will fail because of weird access rights indeed.

Only npm run can launch npm publish.

**Comment by rayrutjes** [comment]
For the reference: https://github.com/yarnpkg/yarn/issues/2935

**Comment by pixelastic** [comment]
For what it's worth, you can check the value of `process.env._` to check if your script is run with `npm` or `yarn` and issue an error if the wrong one is used.

```javascript
  if (!process.env._.match(/npm/)) {
   console.log('This script must be run with "npm run release"');
   console.log('It will not correctly publish to NPM if used with yarn');
    process.exit(1);
  }
```

`process.env._` will contain the path to the `yarn`/`npm` binary used

**Comment by rayrutjes** [comment]
This would add a JS script layer on top of the bash script.
I think the solution could be to forward the process env indeed, or use the bash script directly like I do now which works fine in the end.
