### ISSUE TITLE
rename branch `master` to `main`

### ISSUE THREAD

**Issue by dezren39** [algolia/chunk-text#7]
as a community developer,
i'd like if the primary branch was renamed to `main`,
so as to be more inclusive for all those who may come across this repository.

**Comment by redox** [comment]
Thank you for raising this concern @dezren39 ; we at Algolia care deeply about making sure we create an inclusive community. As we have hundreds of repository on GitHub - and a ton of tooling + scripts related to it -, making such a change won't be that easy so we plan of making the move to `main` once GitHub changes the default.

**Comment by dezren39** [comment]
Sounds good, thanks!
